// East Gate Hotel 2025 - Enhanced Menu with Kinyarwanda & Images
export interface MenuItem {
  id: string;
  name: string; // Kinyarwanda (primary)
  nameEn: string;
  nameFr?: string;
  category: string;
  price: number;
  description?: string;
  descriptionEn?: string;
  image: string;
  available: boolean;
  popular?: boolean;
  vegetarian?: boolean;
  spicy?: boolean;
  halal?: boolean;
  glutenFree?: boolean;
}

export const menuCategories = [
  { id: "bitangura", label: "Bitangura", labelEn: "Starters", icon: "🍲" },
  { id: "inyama-yinka", label: "Inyama y'Inka", labelEn: "Beef", icon: "🥩" },
  { id: "inkoko", label: "Inkoko", labelEn: "Chicken", icon: "🍗" },
  { id: "ifi", label: "Ifi", labelEn: "Fish", icon: "🐟" },
  { id: "ibidasanzwe", label: "Ibidasanzwe", labelEn: "Specials", icon: "⭐" },
  { id: "pasta", label: "Pasta", labelEn: "Pasta", icon: "🍝" },
  { id: "sandwich", label: "Sandwich", labelEn: "Sandwiches", icon: "🥪" },
  { id: "bbq", label: "Barbeque", labelEn: "BBQ", icon: "🔥" },
  { id: "ibigize", label: "Ibigize Ifunguro", labelEn: "Sides", icon: "🍚" },
  { id: "ibinywabura", label: "Ibinywabura", labelEn: "Desserts", icon: "🍰" },
  { id: "ifunguro-gitondo", label: "Ifunguro ryo mu Gitondo", labelEn: "Breakfast", icon: "🍳" },
  { id: "bifeti", label: "Bifeti", labelEn: "Buffet", icon: "🍽️" },
  { id: "ibinyobwa-byoroshye", label: "Ibinyobwa Byoroshye", labelEn: "Soft Drinks", icon: "🥤" },
  { id: "ibinyobwa-byoshye", label: "Ibinyobwa Byoshye", labelEn: "Hot Beverages", icon: "☕" },
  { id: "wines", label: "Wines", labelEn: "Wines", icon: "🍷" },
];

export const enhancedMenu: MenuItem[] = [
  // BITANGURA (STARTERS)
  {
    id: "st-001",
    name: "Brochettes z'Inkoko",
    nameEn: "Chicken Brochettes",
    nameFr: "Brochettes de Poulet",
    category: "bitangura",
    price: 8000,
    description: "Inkoko yokeye kuri gitovu",
    descriptionEn: "Grilled chicken skewers",
    image: "https://images.pexels.com/photos/32754748/pexels-photo-32754748.jpeg",
    available: true,
    popular: true,
    halal: true,
  },
  {
    id: "st-002",
    name: "Sambaza Zokeye",
    nameEn: "Fried Sambaza",
    category: "bitangura",
    price: 7000,
    description: "Sambaza zokeye mu mafuta",
    descriptionEn: "Crispy fried lake sardines",
    image: "https://images.pexels.com/photos/8352785/pexels-photo-8352785.jpeg",
    available: true,
  },

  // INYAMA Y'INKA (BEEF)
  {
    id: "bf-001",
    name: "Steak ya Fillet",
    nameEn: "Fillet Steak",
    category: "inyama-yinka",
    price: 34000,
    description: "Inyama y'inka yokeye kuri gitovu",
    descriptionEn: "Tender grilled beef fillet",
    image: "https://images.pexels.com/photos/19774527/pexels-photo-19774527.jpeg",
    available: true,
    popular: true,
    glutenFree: true,
  },
  {
    id: "bf-002",
    name: "T-Bone Steak",
    nameEn: "T-Bone Steak",
    category: "inyama-yinka",
    price: 36000,
    description: "Steak nini y'inyama y'inka",
    descriptionEn: "Large T-bone steak",
    image: "https://images.pexels.com/photos/30350296/pexels-photo-30350296.jpeg",
    available: true,
    glutenFree: true,
  },
  {
    id: "bf-003",
    name: "Beef Stroganoff",
    nameEn: "Beef Stroganoff",
    category: "inyama-yinka",
    price: 28000,
    description: "Inyama y'inka mu sauce nziza",
    descriptionEn: "Beef in creamy mushroom sauce",
    image: "https://images.pexels.com/photos/27305268/pexels-photo-27305268.jpeg",
    available: true,
  },
  {
    id: "bf-004",
    name: "Brochette z'Inyama",
    nameEn: "Beef Brochette",
    category: "inyama-yinka",
    price: 10000,
    description: "Inyama yokeye kuri gitovu",
    descriptionEn: "Grilled beef skewers",
    image: "https://images.pexels.com/photos/31126183/pexels-photo-31126183.jpeg",
    available: true,
  },

  // INKOKO (CHICKEN)
  {
    id: "ch-001",
    name: "Inkoko Yokeye n'Umuceri",
    nameEn: "Grilled Chicken with Rice",
    category: "inkoko",
    price: 18000,
    description: "Inkoko yokeye hamwe n'umuceri",
    descriptionEn: "Grilled chicken with steamed rice",
    image: "https://images.unsplash.com/photo-1763627719029-d7122ae87e8f",
    available: true,
    popular: true,
    halal: true,
  },
  {
    id: "ch-002",
    name: "Inkoko Yokeye mu Mafuta",
    nameEn: "Fried Chicken",
    category: "inkoko",
    price: 16000,
    description: "Inkoko yokeye mu mafuta",
    descriptionEn: "Crispy fried chicken",
    image: "https://images.pexels.com/photos/12916879/pexels-photo-12916879.jpeg",
    available: true,
    halal: true,
  },
  {
    id: "ch-003",
    name: "Chicken Curry",
    nameEn: "Chicken Curry",
    category: "inkoko",
    price: 19000,
    description: "Inkoko mu sauce ya curry",
    descriptionEn: "Spicy chicken curry",
    image: "https://images.pexels.com/photos/6646212/pexels-photo-6646212.jpeg",
    available: true,
    spicy: true,
    halal: true,
  },

  // IFI (FISH)
  {
    id: "fs-001",
    name: "Tilapia Yokeye",
    nameEn: "Grilled Tilapia",
    category: "ifi",
    price: 23400,
    description: "Tilapia y'ikirere yokeye kuri gitovu",
    descriptionEn: "Fresh grilled tilapia",
    image: "https://images.unsplash.com/photo-1665582038443-7d55b4673c57",
    available: true,
    popular: true,
    glutenFree: true,
  },
  {
    id: "fs-002",
    name: "Nile Perch",
    nameEn: "Nile Perch Fillet",
    category: "ifi",
    price: 26000,
    description: "Ifi ya Nile Perch",
    descriptionEn: "Grilled Nile perch",
    image: "https://images.pexels.com/photos/28446446/pexels-photo-28446446.jpeg",
    available: true,
  },

  // IBIDASANZWE (SPECIALS)
  {
    id: "sp-001",
    name: "Akabenzi k'Inkoko",
    nameEn: "Chicken Akabenzi",
    category: "ibidasanzwe",
    price: 17000,
    description: "Inkoko mu sauce nziza",
    descriptionEn: "Chicken in special sauce",
    image: "https://images.pexels.com/photos/13915043/pexels-photo-13915043.jpeg",
    available: true,
    popular: true,
    spicy: true,
  },
  {
    id: "sp-002",
    name: "Akabenzi k'Inyama",
    nameEn: "Beef Akabenzi",
    category: "ibidasanzwe",
    price: 21000,
    description: "Inyama y'inka mu sauce",
    descriptionEn: "Beef in special sauce",
    image: "https://images.pexels.com/photos/9546273/pexels-photo-9546273.jpeg",
    available: true,
    spicy: true,
  },
  {
    id: "sp-003",
    name: "Isombe",
    nameEn: "Isombe",
    category: "ibidasanzwe",
    price: 18200,
    description: "Amadodo n'imyumbati",
    descriptionEn: "Cassava leaves with plantains",
    image: "https://images.pexels.com/photos/22735421/pexels-photo-22735421.jpeg",
    available: true,
    popular: true,
    vegetarian: true,
  },
  {
    id: "sp-004",
    name: "Agatogo k'Ibijumba",
    nameEn: "Eggplant Agatogo",
    category: "ibidasanzwe",
    price: 12000,
    description: "Ibijumba mu sauce",
    descriptionEn: "Eggplant in tomato sauce",
    image: "https://images.pexels.com/photos/19141526/pexels-photo-19141526.jpeg",
    available: true,
    vegetarian: true,
  },

  // PASTA
  {
    id: "ps-001",
    name: "Spaghetti Bolognese",
    nameEn: "Spaghetti Bolognese",
    category: "pasta",
    price: 15000,
    description: "Spaghetti n'inyama",
    descriptionEn: "Spaghetti with meat sauce",
    image: "https://images.unsplash.com/photo-1761545832779-bc0b4290fc5e",
    available: true,
    popular: true,
  },
  {
    id: "ps-002",
    name: "Penne Arrabiata",
    nameEn: "Penne Arrabiata",
    category: "pasta",
    price: 14000,
    description: "Penne mu sauce y'inyanya",
    descriptionEn: "Penne in spicy tomato sauce",
    image: "https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg",
    available: true,
    spicy: true,
    vegetarian: true,
  },

  // SANDWICH
  {
    id: "sw-001",
    name: "Club Sandwich",
    nameEn: "Club Sandwich",
    category: "sandwich",
    price: 12000,
    description: "Sandwich hamwe n'inkoko",
    descriptionEn: "Triple-decker sandwich",
    image: "https://images.pexels.com/photos/28681955/pexels-photo-28681955.jpeg",
    available: true,
    popular: true,
  },
  {
    id: "sw-002",
    name: "Sandwich y'Inyama",
    nameEn: "Beef Sandwich",
    category: "sandwich",
    price: 13000,
    description: "Inyama y'inka mu sandwich",
    descriptionEn: "Grilled beef sandwich",
    image: "https://images.pexels.com/photos/5112557/pexels-photo-5112557.jpeg",
    available: true,
  },

  // BBQ
  {
    id: "bbq-001",
    name: "Brochette Platter",
    nameEn: "Mixed Brochette Platter",
    category: "bbq",
    price: 28600,
    description: "Brochettes zinyuranye",
    descriptionEn: "Mixed grilled skewers",
    image: "https://images.pexels.com/photos/6419732/pexels-photo-6419732.jpeg",
    available: true,
    popular: true,
  },
  {
    id: "bbq-002",
    name: "Nyama Choma",
    nameEn: "Nyama Choma",
    category: "bbq",
    price: 32500,
    description: "Inyama yokeye n'ugali",
    descriptionEn: "Flame-grilled beef with ugali",
    image: "https://images.pexels.com/photos/32973156/pexels-photo-32973156.jpeg",
    available: true,
  },

  // IBINYWABURA (DESSERTS)
  {
    id: "ds-001",
    name: "Keke ya Chocolat",
    nameEn: "Chocolate Lava Cake",
    category: "ibinywabura",
    price: 13000,
    description: "Keke ya chocolat n'ice cream",
    descriptionEn: "Warm chocolate cake",
    image: "https://images.pexels.com/photos/33674415/pexels-photo-33674415.jpeg",
    available: true,
    popular: true,
  },
  {
    id: "ds-002",
    name: "Tiramisu",
    nameEn: "Tiramisu",
    category: "ibinywabura",
    price: 11000,
    description: "Tiramisu y'Italiya",
    descriptionEn: "Italian tiramisu",
    image: "https://images.pexels.com/photos/31918529/pexels-photo-31918529.jpeg",
    available: true,
  },

  // IFUNGURO RYO MU GITONDO (BREAKFAST)
  {
    id: "bk-001",
    name: "Ifunguro rya Continental",
    nameEn: "Continental Breakfast",
    category: "ifunguro-gitondo",
    price: 19500,
    description: "Amagi, umugati, imbuto",
    descriptionEn: "Eggs, toast, fresh fruits",
    image: "https://pixabay.com/get/g89f2963b162739f233f7c2e31cf943446d80acd815d86b37efe0caef2988fa2f6e605c5a7778986d78fcb4b49ea68ec1.jpg",
    available: true,
    popular: true,
  },
  {
    id: "bk-002",
    name: "Ifunguro ryo mu Rwanda",
    nameEn: "Rwandan Breakfast",
    category: "ifunguro-gitondo",
    price: 15600,
    description: "Ibijumba, ibishyimbo, umuneke",
    descriptionEn: "Sweet potatoes, beans, banana",
    image: "https://images.pexels.com/photos/2662875/pexels-photo-2662875.jpeg",
    available: true,
  },

  // IBINYOBWA BYOROSHYE (SOFT DRINKS)
  {
    id: "sd-001",
    name: "Umutobe w'Imbuto",
    nameEn: "Fresh Fruit Juice",
    category: "ibinyobwa-byoroshye",
    price: 7800,
    description: "Passion, manga, cyangwa imbuto zivanze",
    descriptionEn: "Passion fruit, mango, or mixed",
    image: "https://images.pexels.com/photos/2479242/pexels-photo-2479242.jpeg",
    available: true,
    popular: true,
  },
  {
    id: "sd-002",
    name: "Coca Cola",
    nameEn: "Coca Cola",
    category: "ibinyobwa-byoroshye",
    price: 3900,
    description: "Coca Cola",
    descriptionEn: "Coca Cola",
    image: "https://images.pexels.com/photos/17146376/pexels-photo-17146376.jpeg",
    available: true,
  },

  // IBINYOBWA BYOSHYE (HOT BEVERAGES)
  {
    id: "hb-001",
    name: "Ikawa yo mu Rwanda",
    nameEn: "Rwandan Coffee",
    category: "ibinyobwa-byoshye",
    price: 6500,
    description: "Ikawa nziza yo mu Rwanda",
    descriptionEn: "Premium Rwandan coffee",
    image: "https://images.unsplash.com/photo-1451271772015-90ecf3644e36",
    available: true,
    popular: true,
  },
  {
    id: "hb-002",
    name: "Icyayi c'Ubuki",
    nameEn: "Honey Tea",
    category: "ibinyobwa-byoshye",
    price: 5000,
    description: "Icyayi hamwe n'ubuki",
    descriptionEn: "Tea with honey",
    image: "https://images.pexels.com/photos/12799305/pexels-photo-12799305.jpeg",
    available: true,
  },

  // WINES
  {
    id: "wn-001",
    name: "Vino Itukura",
    nameEn: "Chilean Cabernet (Red Wine)",
    category: "wines",
    price: 35000,
    description: "Vino nziza ituruka Chile",
    descriptionEn: "Chilean red wine",
    image: "https://images.unsplash.com/photo-1762454016515-f29750071257",
    available: true,
  },
  {
    id: "wn-002",
    name: "Vino Yera",
    nameEn: "South African Sauvignon (White)",
    category: "wines",
    price: 32000,
    description: "Vino yera y'Afurika y'Epfo",
    descriptionEn: "South African white wine",
    image: "https://images.pexels.com/photos/11116806/pexels-photo-11116806.jpeg",
    available: true,
  },
];
