// East Gate Hotel 2025 Complete Menu Data

export type MenuCategory =
  | "hot_starters"
  | "cold_starters"
  | "beef"
  | "chicken"
  | "fish"
  | "specials"
  | "pasta"
  | "sandwiches"
  | "barbeque"
  | "accompaniment"
  | "light_meals"
  | "desserts"
  | "sides"
  | "sizzling"
  | "pizza"
  | "breakfast"
  | "buffet"
  | "hot_beverages"
  | "soft_drinks"
  | "beers"
  | "wines"
  | "spirits"
  | "snacks"
  | "sweets";

export interface MenuItemDetail {
  id: string;
  name: string;
  nameFr?: string;
  category: MenuCategory;
  price: number;
  description?: string;
  available: boolean;
  popular?: boolean;
  spicy?: boolean;
  vegetarian?: boolean;
}

export const menuCategories: Array<{
  id: MenuCategory;
  label: string;
  icon: string;
}> = [
  { id: "hot_starters", label: "Hot Starters & Soups", icon: "🍲" },
  { id: "cold_starters", label: "Cold Starters & Salads", icon: "🥗" },
  { id: "beef", label: "Beef Dishes", icon: "🥩" },
  { id: "chicken", label: "Chicken Dishes", icon: "🍗" },
  { id: "fish", label: "Fish Dishes", icon: "🐟" },
  { id: "specials", label: "East Gate Specials", icon: "⭐" },
  { id: "pasta", label: "Pasta", icon: "🍝" },
  { id: "sandwiches", label: "Sandwiches & Burgers", icon: "🍔" },
  { id: "barbeque", label: "Barbeque", icon: "🍢" },
  { id: "accompaniment", label: "Accompaniments", icon: "🍟" },
  { id: "light_meals", label: "Light Meals", icon: "🌯" },
  { id: "desserts", label: "Desserts", icon: "🍰" },
  { id: "sides", label: "Sides", icon: "🍛" },
  { id: "sizzling", label: "East Gate Sizzling", icon: "🔥" },
  { id: "pizza", label: "East Gate Pizza", icon: "🍕" },
  { id: "breakfast", label: "Breakfast Menu", icon: "🍳" },
  { id: "buffet", label: "Buffet Options", icon: "🍽️" },
  { id: "hot_beverages", label: "Hot Beverages", icon: "☕" },
  { id: "soft_drinks", label: "Soft Drinks & Juices", icon: "🥤" },
  { id: "beers", label: "Beers", icon: "🍺" },
  { id: "wines", label: "Wines", icon: "🍷" },
  { id: "spirits", label: "Spirits", icon: "🥃" },
  { id: "snacks", label: "Bites & Snacks", icon: "🥨" },
  { id: "sweets", label: "Sweets", icon: "🧁" },
];

export const fullMenu: MenuItemDetail[] = [
  // HOT STARTERS/SOUPS
  {
    id: "hs-001",
    name: "Mushroom Soup",
    nameFr: "Soupe de champignons",
    category: "hot_starters",
    price: 3000,
    available: true,
    vegetarian: true,
  },
  {
    id: "hs-002",
    name: "Fish Clear Soup",
    nameFr: "Soupe de poisons",
    category: "hot_starters",
    price: 4000,
    available: true,
  },
  {
    id: "hs-003",
    name: "Vegetable Soup",
    nameFr: "Soupe de legumes",
    category: "hot_starters",
    price: 3000,
    available: true,
    vegetarian: true,
  },
  {
    id: "hs-004",
    name: "Cream of Chicken Soup",
    nameFr: "Veloute de poulet",
    category: "hot_starters",
    price: 4000,
    available: true,
  },
  {
    id: "hs-005",
    name: "Carrot Ginger Soup",
    nameFr: "Soupe de carrotte et gingembre",
    category: "hot_starters",
    price: 3000,
    available: true,
    vegetarian: true,
  },

  // COLD STARTERS/SALADS
  {
    id: "cs-001",
    name: "Garden Salad",
    category: "cold_starters",
    price: 3000,
    description: "Onion, tomato, carrot, cucumber and vinaigrette sauce",
    available: true,
    vegetarian: true,
  },
  {
    id: "cs-002",
    name: "American Salad",
    category: "cold_starters",
    price: 5000,
    description: "Cucumbers, pineapple, tomatoes, eggs, chicken, cheese",
    available: true,
    popular: true,
  },
  {
    id: "cs-003",
    name: "Chef Salad",
    category: "cold_starters",
    price: 5000,
    description: "Onions, tomatoes, carrots, avocados, eggs, cucumber, cheese, broccoli",
    available: true,
  },
  {
    id: "cs-004",
    name: "Nicoise Salad",
    category: "cold_starters",
    price: 5000,
    description: "Boiled eggs, potato, green beans, and dressing sauce",
    available: true,
  },
  {
    id: "cs-005",
    name: "Mexicana Salad",
    category: "cold_starters",
    price: 5000,
    description: "Green beans, sweet corn, avocados, cheese, chicken strips, lemon",
    available: true,
    spicy: true,
  },

  // BEEF
  {
    id: "bf-001",
    name: "Beef Stew",
    category: "beef",
    price: 5000,
    description: "Thai marinated beef cooked in red sauce",
    available: true,
  },
  {
    id: "bf-002",
    name: "Beef Steak",
    category: "beef",
    price: 8000,
    description: "Tender beef fillet in pepper sauce with choice of doneness",
    available: true,
    popular: true,
  },
  {
    id: "bf-003",
    name: "Beef Stroganoff",
    category: "beef",
    price: 8000,
    description: "Beef fillet, creamed mushroom, green pepper and onion",
    available: true,
  },
  {
    id: "bf-004",
    name: "Beef Curry",
    category: "beef",
    price: 8000,
    description: "Beef in curry sauce + accompaniments",
    available: true,
    spicy: true,
  },

  // CHICKEN
  {
    id: "ch-001",
    name: "Chicken Curry",
    category: "chicken",
    price: 8000,
    description: "Chicken in curry sauce + accompaniments",
    available: true,
    spicy: true,
  },
  {
    id: "ch-002",
    name: "Roasted ¼ Chicken",
    category: "chicken",
    price: 8000,
    available: true,
    popular: true,
  },
  {
    id: "ch-003",
    name: "Chicken Stroganoff",
    category: "chicken",
    price: 8000,
    description: "¼ chicken, creamed mushroom, green pepper and white sauce",
    available: true,
  },
  {
    id: "ch-004",
    name: "East Gate Hot Pot ¼ Chicken",
    category: "chicken",
    price: 8000,
    description: "Chicken gisafuriya of bananas/potatoes/nuts & vegetables",
    available: true,
  },
  {
    id: "ch-005",
    name: "East Gate Whole Pot Chicken",
    category: "chicken",
    price: 20000,
    description: "Igisafuriya/Chicken, spices, banana/potatoes, vegetables",
    available: true,
  },
  {
    id: "ch-006",
    name: "Roasted Whole Chicken",
    nameFr: "Poulet de chair",
    category: "chicken",
    price: 18000,
    description: "Without accompaniment",
    available: true,
  },
  {
    id: "ch-007",
    name: "East Gate ½ Chicken Steak",
    category: "chicken",
    price: 10000,
    available: true,
  },
  {
    id: "ch-008",
    name: "East Gate ¼ Local Chicken Stew",
    category: "chicken",
    price: 8000,
    available: true,
  },
  {
    id: "ch-009",
    name: "East Gate Special Chicken",
    category: "chicken",
    price: 20000,
    available: true,
    popular: true,
  },
  {
    id: "ch-010",
    name: "Chicken Cordon-bleu",
    category: "chicken",
    price: 10000,
    available: true,
  },
  {
    id: "ch-011",
    name: "Local Grilled Whole Chicken",
    category: "chicken",
    price: 16000,
    description: "Without accompaniment",
    available: true,
  },
  {
    id: "ch-012",
    name: "Chicken Brochette",
    category: "chicken",
    price: 3500,
    available: true,
  },

  // FISH
  {
    id: "fs-001",
    name: "Fish Curry",
    category: "fish",
    price: 8000,
    description: "Fish in curry sauce + accompaniments",
    available: true,
    spicy: true,
  },
  {
    id: "fs-002",
    name: "Whole Grilled Tilapia Fish",
    category: "fish",
    price: 18000,
    description: "Without accompaniment",
    available: true,
    popular: true,
  },
  {
    id: "fs-003",
    name: "Fish Brochette",
    category: "fish",
    price: 3500,
    available: true,
  },

  // EAST GATE SPECIALS
  {
    id: "sp-001",
    name: "Akabenzi (0.5kg)",
    category: "specials",
    price: 6000,
    description: "Fried pork with authentic herbs",
    available: true,
    popular: true,
  },
  {
    id: "sp-002",
    name: "Akabenzi (1kg)",
    category: "specials",
    price: 10000,
    description: "Fried pork with authentic herbs",
    available: true,
    popular: true,
  },
  {
    id: "sp-003",
    name: "Agatogo",
    category: "specials",
    price: 5000,
    description: "Beef with banana and vegetables, spices",
    available: true,
  },
  {
    id: "sp-004",
    name: "Special East Gate Goat",
    category: "specials",
    price: 150000,
    description: "Braised goat, pilau rice and kachumbali salad",
    available: true,
  },

  // PASTA
  {
    id: "ps-001",
    name: "Spaghetti Primavera",
    category: "pasta",
    price: 5000,
    description: "Spaghetti vegetarian with cheese",
    available: true,
    vegetarian: true,
  },
  {
    id: "ps-002",
    name: "Spaghetti Bolognaise",
    category: "pasta",
    price: 6000,
    description: "Minced meat in tomato sauce with herbs",
    available: true,
  },
  {
    id: "ps-003",
    name: "Penne Napolitaine",
    category: "pasta",
    price: 5000,
    description: "Macaroni, tomatoes, celeries, red pepper, basil cheese",
    available: true,
    vegetarian: true,
  },

  // SANDWICHES/BURGERS
  {
    id: "sb-001",
    name: "Club Sandwich",
    category: "sandwiches",
    price: 6000,
    description: "Chicken, eggs, lettuce, ham, cheese, chips",
    available: true,
  },
  {
    id: "sb-002",
    name: "Cheese Burger",
    category: "sandwiches",
    price: 6000,
    description: "Burger bun, beef, cheese, lettuce, onion, tomatoes, chips",
    available: true,
  },
  {
    id: "sb-003",
    name: "Chicken Burger",
    category: "sandwiches",
    price: 7000,
    description: "Burger bun, chicken, onion, lettuce, tomatoes, chips",
    available: true,
  },

  // BARBEQUE
  {
    id: "bb-001",
    name: "Goat Brochette",
    category: "barbeque",
    price: 2000,
    available: true,
    popular: true,
  },
  {
    id: "bb-002",
    name: "Beef Brochette",
    category: "barbeque",
    price: 3000,
    available: true,
  },

  // ACCOMPANIMENT
  {
    id: "ac-001",
    name: "Plain Chips & Salad",
    category: "accompaniment",
    price: 2000,
    available: true,
  },
  {
    id: "ac-002",
    name: "Fried Rice with Sauce",
    category: "accompaniment",
    price: 2000,
    available: true,
  },
  {
    id: "ac-003",
    name: "Pomme Sauté (4pcs)",
    category: "accompaniment",
    price: 2000,
    available: true,
  },
  {
    id: "ac-004",
    name: "Pomme Purée",
    category: "accompaniment",
    price: 4000,
    description: "Mashed potato",
    available: true,
  },
  {
    id: "ac-005",
    name: "Grilled Banana (1pc)",
    category: "accompaniment",
    price: 600,
    available: true,
  },
  {
    id: "ac-006",
    name: "Banana Chips",
    category: "accompaniment",
    price: 2000,
    available: true,
  },
  {
    id: "ac-007",
    name: "Grilled Potato (1pc)",
    category: "accompaniment",
    price: 600,
    available: true,
  },
  {
    id: "ac-008",
    name: "Vegetable Meals",
    nameFr: "Repas Vegetarien",
    category: "accompaniment",
    price: 4000,
    available: true,
    vegetarian: true,
  },

  // LIGHT MEALS
  {
    id: "lm-001",
    name: "East Gate Chapati Wrap",
    category: "light_meals",
    price: 5000,
    description: "Chapati wrap, chicken/beef served with salads, chips",
    available: true,
  },
  {
    id: "lm-002",
    name: "Fish Fingers with Chips and Salad",
    category: "light_meals",
    price: 6000,
    available: true,
  },
  {
    id: "lm-003",
    name: "Chicken Wings",
    category: "light_meals",
    price: 6000,
    available: true,
  },
  {
    id: "lm-004",
    name: "Amuse Gueules Mixte",
    category: "light_meals",
    price: 5000,
    description: "Fried sausage or fried meat, cheese",
    available: true,
  },

  // DESSERTS
  {
    id: "ds-001",
    name: "Tropical Fruits Cuts",
    category: "desserts",
    price: 6000,
    description: "Mixed fruits",
    available: true,
    vegetarian: true,
  },
  {
    id: "ds-002",
    name: "Macédoine de Fruits",
    category: "desserts",
    price: 4000,
    description: "Fruits salad",
    available: true,
    vegetarian: true,
  },

  // SIDES
  {
    id: "sd-001",
    name: "Kawunga with Beef Stew",
    category: "sides",
    price: 5000,
    available: true,
  },
  {
    id: "sd-002",
    name: "Kaunga Christine",
    category: "sides",
    price: 6000,
    description: "Vegetables spiced aubergine, beef meat and peanut, garlic",
    available: true,
  },
  {
    id: "sd-003",
    name: "Ugali with Beef Stew and Vegetables",
    category: "sides",
    price: 5000,
    available: true,
  },
  {
    id: "sd-004",
    name: "Special Omelet",
    category: "sides",
    price: 5000,
    available: true,
  },

  // SIZZLING
  {
    id: "sz-001",
    name: "Sizzling Fish",
    category: "sizzling",
    price: 8000,
    available: true,
  },
  {
    id: "sz-002",
    name: "Sizzling Chicken",
    category: "sizzling",
    price: 8000,
    available: true,
  },
  {
    id: "sz-003",
    name: "Sizzling Beef",
    category: "sizzling",
    price: 8000,
    available: true,
  },
  {
    id: "sz-004",
    name: "Sizzling Vegetable",
    category: "sizzling",
    price: 8000,
    available: true,
    vegetarian: true,
  },

  // PIZZA
  {
    id: "pz-001",
    name: "East Gate Special Pizza",
    category: "pizza",
    price: 8000,
    description: "Potatoes, tomato, cauliflower, cream, cheese",
    available: true,
    popular: true,
  },
  {
    id: "pz-002",
    name: "Vegetarian Pizza",
    category: "pizza",
    price: 7000,
    description: "Potatoes, mushroom, tomato, green pepper, cream cheese",
    available: true,
    vegetarian: true,
  },

  // BREAKFAST
  {
    id: "br-001",
    name: "Ordinary Breakfast",
    category: "breakfast",
    price: 5000,
    description: "Omelet, snacks, tea",
    available: true,
  },
  {
    id: "br-002",
    name: "Continental Breakfast",
    category: "breakfast",
    price: 7000,
    description: "Tea, snacks, omelet, & 2 kinds of fruit",
    available: true,
  },
  {
    id: "br-003",
    name: "English Breakfast",
    category: "breakfast",
    price: 10000,
    description: "Hot dish, 3 kinds of fruits, soup or quaker, snacks, tea, omelet, juice",
    available: true,
  },

  // BUFFET
  {
    id: "bu-001",
    name: "Ordinary Buffet",
    category: "buffet",
    price: 8500,
    description: "Mixed salad or soup, green banana, rice, chips, vegetables, local dish, beef meat, dessert (1 fruit), soft drink",
    available: true,
  },
  {
    id: "bu-002",
    name: "Medium Buffet",
    category: "buffet",
    price: 9500,
    description: "Mixed salad or soup, green banana, rice, chips, vegetables, local dish, chicken meat, dessert (2 fruits), soft drink",
    available: true,
  },
  {
    id: "bu-003",
    name: "Standard Buffet",
    category: "buffet",
    price: 15000,
    description: "Mixed soup, bread & salad, green banana, rice, chips, vegetables, beans, local dish, beef & chicken meat, dessert (2 fruits), soft drink",
    available: true,
    popular: true,
  },
  {
    id: "bu-004",
    name: "Executive Buffet",
    category: "buffet",
    price: 20000,
    description: "Hot & cold starter, green/mashed banana/potatoes, rice, chips, vegetables, beans, posho, local dishes, beef, fish & chicken meat, dessert (3 fruits & fresh juice), soft drink",
    available: true,
  },

  // HOT BEVERAGES
  {
    id: "hb-001",
    name: "Black Tea",
    category: "hot_beverages",
    price: 1500,
    available: true,
  },
  {
    id: "hb-002",
    name: "Green Tea",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },
  {
    id: "hb-003",
    name: "African Tea",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },
  {
    id: "hb-004",
    name: "Spice Tea",
    category: "hot_beverages",
    price: 3000,
    available: true,
  },
  {
    id: "hb-005",
    name: "Ginger Tea",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },
  {
    id: "hb-006",
    name: "Lemon Tea",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },
  {
    id: "hb-007",
    name: "Hot Water",
    category: "hot_beverages",
    price: 1000,
    available: true,
  },
  {
    id: "hb-008",
    name: "English Tea / Tea Nido",
    category: "hot_beverages",
    price: 5000,
    available: true,
  },
  {
    id: "hb-009",
    name: "African Coffee",
    category: "hot_beverages",
    price: 2500,
    available: true,
  },
  {
    id: "hb-010",
    name: "Black Coffee",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },
  {
    id: "hb-011",
    name: "Hot Chocolate",
    category: "hot_beverages",
    price: 4000,
    available: true,
  },
  {
    id: "hb-012",
    name: "Hot Milk",
    category: "hot_beverages",
    price: 2000,
    available: true,
  },

  // SOFT DRINKS
  {
    id: "sd-101",
    name: "Assorted Soda / Fanta",
    category: "soft_drinks",
    price: 1000,
    available: true,
  },
  {
    id: "sd-102",
    name: "Coca Cola (Plastic Bottle)",
    category: "soft_drinks",
    price: 1500,
    available: true,
  },
  {
    id: "sd-103",
    name: "Mineral Water",
    category: "soft_drinks",
    price: 1000,
    available: true,
  },
  {
    id: "sd-104",
    name: "Sparkling Water",
    category: "soft_drinks",
    price: 1500,
    available: true,
  },
  {
    id: "sd-105",
    name: "Packed Juice (500ml)",
    category: "soft_drinks",
    price: 1500,
    available: true,
  },
  {
    id: "sd-106",
    name: "Fresh Juice",
    category: "soft_drinks",
    price: 6000,
    available: true,
  },
  {
    id: "sd-107",
    name: "Eau Gazeuse",
    category: "soft_drinks",
    price: 1500,
    available: true,
  },
  {
    id: "sd-108",
    name: "Panache",
    category: "soft_drinks",
    price: 1000,
    available: true,
  },
  {
    id: "sd-109",
    name: "Red Bull",
    category: "soft_drinks",
    price: 4000,
    available: true,
  },
  {
    id: "sd-110",
    name: "Bavaria (N/A)",
    category: "soft_drinks",
    price: 4000,
    available: true,
  },

  // BEERS
  {
    id: "be-001",
    name: "Skol Malt / Mutzig / Virunga (33cl)",
    category: "beers",
    price: 1500,
    available: true,
  },
  {
    id: "be-002",
    name: "Primus (50cl)",
    category: "beers",
    price: 1500,
    available: true,
  },
  {
    id: "be-003",
    name: "Amstel",
    category: "beers",
    price: 2000,
    available: true,
  },
  {
    id: "be-004",
    name: "Heineken",
    category: "beers",
    price: 2000,
    available: true,
  },
  {
    id: "be-005",
    name: "Smirnoff Guarana",
    category: "beers",
    price: 4000,
    available: true,
  },
  {
    id: "be-006",
    name: "Leffe (Bottle)",
    category: "beers",
    price: 6000,
    available: true,
  },
  {
    id: "be-007",
    name: "Leffe (Cannette)",
    category: "beers",
    price: 3500,
    available: true,
  },
  {
    id: "be-008",
    name: "EXO",
    category: "beers",
    price: 4000,
    available: true,
  },

  // WINES
  {
    id: "wn-001",
    name: "House Wine (Glass) - Red/White, Sweet/Dry",
    category: "wines",
    price: 4000,
    available: true,
  },
  {
    id: "wn-002",
    name: "The Four Cousins Sweet (1L) - White",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-003",
    name: "Cellar Cask (1L) - White",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-004",
    name: "Cellar Cask (5L) - White",
    category: "wines",
    price: 100000,
    available: true,
  },
  {
    id: "wn-005",
    name: "Pintanegra (1L) - White",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-006",
    name: "The Four Cousins Dry/Sweet (1L) - Red",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-007",
    name: "Chivalac (1L) - Red",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-008",
    name: "PintaNegra Dry/Sweet (1L) - Red",
    category: "wines",
    price: 30000,
    available: true,
  },
  {
    id: "wn-009",
    name: "PintaNegra Dry/Sweet (5L) - Red",
    category: "wines",
    price: 100000,
    available: true,
  },
  {
    id: "wn-010",
    name: "Drosty Dry/Sweet (1L) - Red",
    category: "wines",
    price: 30000,
    available: true,
  },

  // SPIRITS
  {
    id: "sp-101",
    name: "Amarula (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-102",
    name: "Amarula (Full Bottle)",
    category: "spirits",
    price: 60000,
    available: true,
  },
  {
    id: "sp-103",
    name: "Martini Bianco/Rosso (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-104",
    name: "Martini Bianco/Rosso (Full Bottle)",
    category: "spirits",
    price: 60000,
    available: true,
  },
  {
    id: "sp-105",
    name: "J&B (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-106",
    name: "J&B (Full Bottle)",
    category: "spirits",
    price: 60000,
    available: true,
  },
  {
    id: "sp-107",
    name: "Red Label (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-108",
    name: "Red Label (Full Bottle)",
    category: "spirits",
    price: 60000,
    available: true,
  },
  {
    id: "sp-109",
    name: "Black Label (1/4 Bottle)",
    category: "spirits",
    price: 30000,
    available: true,
  },
  {
    id: "sp-110",
    name: "Black Label (Full Bottle)",
    category: "spirits",
    price: 100000,
    available: true,
  },
  {
    id: "sp-111",
    name: "Double Black (1/4 Bottle)",
    category: "spirits",
    price: 40000,
    available: true,
  },
  {
    id: "sp-112",
    name: "Double Black (Full Bottle)",
    category: "spirits",
    price: 120000,
    available: true,
  },
  {
    id: "sp-113",
    name: "Hennessey V.S (1/4 Bottle)",
    category: "spirits",
    price: 50000,
    available: true,
  },
  {
    id: "sp-114",
    name: "Hennessey V.S (Full Bottle)",
    category: "spirits",
    price: 150000,
    available: true,
  },
  {
    id: "sp-115",
    name: "Remy Martin (1/4 Bottle)",
    category: "spirits",
    price: 50000,
    available: true,
  },
  {
    id: "sp-116",
    name: "Remy Martin (Full Bottle)",
    category: "spirits",
    price: 150000,
    available: true,
  },
  {
    id: "sp-117",
    name: "Chivas Regal (1/4 Bottle)",
    category: "spirits",
    price: 40000,
    available: true,
  },
  {
    id: "sp-118",
    name: "Chivas Regal (Full Bottle)",
    category: "spirits",
    price: 120000,
    available: true,
  },
  {
    id: "sp-119",
    name: "Jameson (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-120",
    name: "Jameson (Full Bottle)",
    category: "spirits",
    price: 70000,
    available: true,
  },
  {
    id: "sp-121",
    name: "Jack Daniel's (1/4 Bottle)",
    category: "spirits",
    price: 35000,
    available: true,
  },
  {
    id: "sp-122",
    name: "Jack Daniel's (Full Bottle)",
    category: "spirits",
    price: 120000,
    available: true,
  },
  {
    id: "sp-123",
    name: "Tequila Camino (1/4 Bottle)",
    category: "spirits",
    price: 30000,
    available: true,
  },
  {
    id: "sp-124",
    name: "Tequila Camino (Full Bottle)",
    category: "spirits",
    price: 70000,
    available: true,
  },
  {
    id: "sp-125",
    name: "Gordon's Gin (1/4 Bottle)",
    category: "spirits",
    price: 25000,
    available: true,
  },
  {
    id: "sp-126",
    name: "Gordon's Gin (Full Bottle)",
    category: "spirits",
    price: 60000,
    available: true,
  },
  {
    id: "sp-127",
    name: "Konyagi (1/2 Bottle)",
    category: "spirits",
    price: 8000,
    available: true,
  },
  {
    id: "sp-128",
    name: "Konyagi (1/4 Bottle)",
    category: "spirits",
    price: 4000,
    available: true,
  },
  {
    id: "sp-129",
    name: "Gordon's (1/2 Bottle)",
    category: "spirits",
    price: 40000,
    available: true,
  },

  // SNACKS
  {
    id: "sn-001",
    name: "Croissant (1pc)",
    category: "snacks",
    price: 1000,
    available: true,
  },
  {
    id: "sn-002",
    name: "Beef Mini Samosa (4pcs)",
    category: "snacks",
    price: 2000,
    available: true,
  },
  {
    id: "sn-003",
    name: "Ham & Cheese Sandwich",
    category: "snacks",
    price: 3000,
    available: true,
  },
  {
    id: "sn-004",
    name: "Cheese & Tomato Sandwich",
    category: "snacks",
    price: 3000,
    available: true,
  },
  {
    id: "sn-005",
    name: "Tuna Sandwich",
    category: "snacks",
    price: 3000,
    available: true,
  },
  {
    id: "sn-006",
    name: "Vegetable Spring Rolls (4pcs)",
    category: "snacks",
    price: 2000,
    available: true,
    vegetarian: true,
  },
  {
    id: "sn-007",
    name: "Cheese & Sausage Platter",
    category: "snacks",
    price: 4000,
    available: true,
  },
  {
    id: "sn-008",
    name: "Plain Chapatti",
    category: "snacks",
    price: 500,
    available: true,
    vegetarian: true,
  },
  {
    id: "sn-009",
    name: "Meat Ball",
    category: "snacks",
    price: 500,
    available: true,
  },

  // SWEETS
  {
    id: "sw-001",
    name: "Lemon Cake",
    category: "sweets",
    price: 1000,
    available: true,
  },
  {
    id: "sw-002",
    name: "Chocolate Cake",
    category: "sweets",
    price: 1000,
    available: true,
  },
  {
    id: "sw-003",
    name: "Muffin",
    category: "sweets",
    price: 1000,
    available: true,
  },
];
